{
 "title": "Satellite Overview",
 "tags": [
  "satellite",
  "telemetry"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SC STATE",
   "type": "stat",
   "description": "the current state of the spacecraft",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SC_STATE\")\n\n  "
    }
   ]
  },
  {
   "title": "ADCS Mode",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"ADCS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MODE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DEPLOYMENT_STATUS\")\n\n  "
    }
   ]
  },
  {
   "title": "Battery Temperature (°C)",
   "type": "stat",
   "description": "the last measured acquired mainboard temp",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_TEMPERATURE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 100.0\n  }))\n  "
    }
   ]
  },
  {
   "title": "SD USAGE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"STORAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SD_TOTAL_USAGE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value)\n  }))\n  "
    }
   ]
  },
  {
   "title": "Battery TTE",
   "type": "stat",
   "description": "how many seconds until battery empty",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_TTE\")\n\n  "
    }
   ]
  },
  {
   "title": "Jetson Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"JETSON_INPUT_VOLTAGE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 1000.0\n  }))\n  "
    }
   ]
  },
  {
   "title": "GPS Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GPS_VOLTAGE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 1000.0\n  }))\n  "
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CURRENT_RAM_USAGE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Battery State of Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_REPORTED_SOC\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Detumbling Error Flag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DETUMBLING_ERROR_FLAG\")\n"
    }
   ]
  },
  {
   "title": "Mainboard Temperature (°C)",
   "type": "stat",
   "description": "the last measured acquired mainboard temp",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAINBOARD_TEMPERATURE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 100.0\n  }))\n  "
    }
   ]
  },
  {
   "title": "GPS FIX",
   "type": "stat",
   "description": "how many seconds until battery full",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"GPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GPS_FIX_MODE\")\n\n  "
    }
   ]
  },
  {
   "title": "Battery TTF",
   "type": "stat",
   "description": "how many seconds until battery full",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BATTERY_PACK_TTF\")\n\n  "
    }
   ]
  },
  {
   "title": "Radio Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RF_LDO_OUTPUT_VOLTAGE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 1000.0\n  }))\n  "
    }
   ]
  },
  {
   "title": "Mainboard Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAINBOARD_VOLTAGE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 1000.0\n  }))\n  "
    }
   ]
  },
  {
   "title": "SC Time",
   "type": "timeseries",
   "description": "the current spacecraft time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TIME\")"
    }
   ]
  },
  {
   "title": "Current Ram Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CURRENT_RAM_USAGE\")"
    }
   ]
  },
  {
   "title": "Boot Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BOOT_COUNT\")"
    }
   ]
  },
  {
   "title": "COMMS_COUNTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"COMMS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RX_PACKET_COUNT\" or r[\"_field\"] == \"TX_PACKET_COUNT\")"
    }
   ]
  },
  {
   "title": "BOOT_TIME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"CDH\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BOOT_TIME\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value)\n  }))"
    }
   ]
  },
  {
   "title": "Mainboard Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAINBOARD_TEMPERATURE\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 100.0\n  }))"
    }
   ]
  },
  {
   "title": "Power System Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAINBOARD_VOLTAGE\" or \n  r[\"_field\"] == \"BATTERY_PACK_VOLTAGE\" or \n  r[\"_field\"]  ==  \"RF_LDO_OUTPUT_VOLTAGE\" or\n  r[\"_field\"]  ==  \"GPS_VOLTAGE\" or\n  r[\"_field\"]  ==  \"BATTERY_PACK_MIDPOINT_VOLTAGE\")\n"
    }
   ]
  },
  {
   "title": "Power System Currents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"EPS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAINBOARD_CURRENT\" or \n  r[\"_field\"] == \"BATTERY_PACK_CURRENT\" or \n  r[\"_field\"]  ==  \"RF_LDO_OUTPUT_CURRENT\" or\n  r[\"_field\"]  ==  \"GPS_CURRENT\")"
    }
   ]
  },
  {
   "title": "Gyroscope (Angular Velocity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"ADCS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GYRO_X\" or r[\"_field\"] == \"GYRO_Y\" or r[\"_field\"] == \"GYRO_Z\")"
    }
   ]
  },
  {
   "title": "Magnetometer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"ADCS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAG_X\" or r[\"_field\"] == \"MAG_Y\" or r[\"_field\"] == \"MAG_Z\")"
    }
   ]
  },
  {
   "title": "Light Sensors (Solar Panels)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"ADCS\")\n  |> filter(fn: (r) => contains(\n    value: r[\"_field\"],\n    set: [\n      \"LIGHT_SENSOR_XP\",\n      \"LIGHT_SENSOR_XM\",\n      \"LIGHT_SENSOR_YP\",\n      \"LIGHT_SENSOR_YM\",\n      \"LIGHT_SENSOR_ZP_XP\",\n      \"LIGHT_SENSOR_ZP_YM\",\n      \"LIGHT_SENSOR_ZP_XM\",\n      \"LIGHT_SENSOR_ZP_YP\",\n      \"LIGHT_SENSOR_ZM\"\n    ]\n  ))"
    }
   ]
  },
  {
   "title": "Sun Vector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"subsystem\"] == \"ADCS\")\n  |> filter(fn: (r) => contains(\n    value: r[\"_field\"],\n    set: [\n      \"SUN_VEC_X\",\n      \"SUN_VEC_Y\",\n      \"SUN_VEC_Z\",\n    ]\n  ))"
    }
   ]
  }
 ]
}